### ISSUE TITLE
Switch from wallet in dApp store

### ISSUE THREAD

**Issue by fiexer** [AstarNetwork/astar-apps#48] opened 2021-10-07 22:21 UTC
**Motivation**
If you use multiple accounts, you have to go first to your balance before seeing staking amount of that wallet.

**Suggested Solution**
Make it possible to easily switch from wallet in the dApp store page

**Alternatives**
/

**Additional Information**
/

**Comment by hoonsubin** [comment] 2021-10-08 07:42
duplicate of https://github.com/PlasmNetwork/astar-apps/issues/29

**Closed as completed** 2021-10-14 09:24 UTC
Labels: duplicate, enhancement, P3, portal ui
