### ISSUE TITLE
Issues connecting to Astar Portal

### ISSUE THREAD

**Issue by NamPhamc99** [AstarNetwork/astar-apps#494] opened 2022-08-30 07:08 UTC
**Describe the bug**
I keep encounter unexpected behaviours connecting to Astar Portal. I primarily use SubWallet but i also encounter problems with Talisman and MetaMask.

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser: Brave

- [x] Not displaying popup on switching wallets
Demo: https://user-images.githubusercontent.com/44641118/187373716-f2e32658-123b-4a08-8c47-71bc898b20ee.mp4
- [x] Displaying multiple popups from different wallets, cannot cancel popup
Demo: https://user-images.githubusercontent.com/44641118/187373704-d319993e-1ac9-4ed3-aff5-76c2b6ee066c.mp4
- [x] Displaying 'wallet not installed' modal
Demo: https://user-images.githubusercontent.com/44641118/187373706-108b02f7-142d-4aa8-a92e-275ccd577e45.mp4
- [x] Cannot detect accounts on SubWallet
Demo: https://user-images.githubusercontent.com/44641118/187373693-b05467b6-a9c8-4557-948d-c6d5472d4841.mp4

**Comment by impelcrypto** [comment] 2022-09-06 10:21
>  Not displaying popup on switching wallets

I can't reproduce the issue. Perhaps you can remove your localstorage and try it again?
https://www.loom.com/share/443661ea3449418c898a26fe1b27f4e3

**Comment by impelcrypto** [comment] 2022-09-06 13:30
@NamPhamc99 
Please test it again at this [staging](https://astar-apps--pr501-fix-connect-wallet-xgr7ryoq.web.app/) URL.

**Comment by NamPhamc99** [comment] 2022-09-14 08:03
Hello @impelcrypto, i see that most of the problems mentioned have been fixed. I actually found a couple of issues with this staging versions.

- [ ] Not displaying connected wallet upon reloading page
    Steps to reproduce:
        1. Connect to a Substrate account (with SubWallet Native)
        2. Switch wallet to SubWallet EVM
        3. Upon the display of popup, cancel the authorization request
        4. Reload the app
    Actual: Not showing connected wallet on the app (i suspect that on step 2, that selectedWallet is changed but the authorization did not go through)

- [ ] Not displaying authorizing popup upon switching wallet
    Steps to reproduce:
        1. Choose SubWallet Native but cancel the authorization popup
        2. Choose MetaMask and authorize the MetaMask account
        3. Switch to SubWallet Native again and authorize the wallets
     Actual: On step 3, the authorization popup doesn't show when SubWallet Native is selected

Note: Overall i think this staging version works well with most of the cases. The basic flows and use cases work well. The issues that i discovered are fairly hard to reproduce so i think it won't happen too often in production. These issues usually happen when the user switches wallet. It's pretty hard to coordinate multiple wallets on 1 dapp so maybe Astar team can come up with a general way to handle these cases

**Comment by impelcrypto** [comment] 2022-09-19 14:08
>  Not displaying connected wallet upon reloading page

It seems like I can't reproduce this on my end.
https://www.loom.com/share/c701b8d0e04a40eebe14459ffd40e99a

**Comment by impelcrypto** [comment] 2022-09-19 14:45
> Not displaying connected wallet upon reloading page

I've reproduced the issue but I don't think users will reload the page (#4) without selecting account. There will be no issue if users select wallet (SubWallet native) in #4.

https://user-images.githubusercontent.com/92044428/191044882-a9a47d33-0eac-4055-adf3-fd631789fdec.mov

**Comment by impelcrypto** [comment] 2022-09-19 14:46
> Not displaying authorizing popup upon switching wallet

If users have canceled authorization before, I think users have to give the authorization by themself on the wallet configuration (Network Settings in SubWallet), at least the issue can be fixed in this way.

**Closed** 2022-09-22 07:56 UTC
Labels: bug
